name: Generate Animation

on:
  push:
    branches:
      - main

jobs:
  generate_animation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate animation (using a tool/script)
      run: |
        convert -size 300x300 xc:skyblue -draw "text 100,150 'Animation'" animation.gif

    - name: Commit and push animation to repo
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Update animation'
