name: lowlighter metrics

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:      # allow manual trigger



jobs:
  generate:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:        
      - name: fetch fortune
        uses: lowlighter/metrics@latest
        with:
          filename: lowlighter/metrics.plugin.fortune.svg
          base: ""
          token: NOT_NEEDED
          plugin_fortune: yes

      - name: language stats
        uses: lowlighter/metrics@latest
        with:
          filename: lowlighter/language-stats.svg
          # outputs: dist/language-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          # plugin_languages_threshold: yes
          commits_authoring: adam jamro, adamjamro, adamjamrozinski02@gmail.com

      - name: repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: lowlighter/metrics.plugin.lines.history.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
          repositories_skipped:
