name: LowlighterMetrics

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:      # allow manual trigger

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      # - name: create dist
      #   run: mkdir -p dist
        
      - name: fetch fortune
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.fortune.svg
          base: ""
          token: NOT_NEEDED
          plugin_fortune: yes

      - name: language stats
        uses: lowlighter/metrics@latest
        with:
          # filename: language-stats.svg
          outputs: dist/language-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          # plugin_languages_threshold: yes
          commits_authoring: adam jamro, adamjamro, adamjamrozinski02@gmail.com

      - name: repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.lines.history.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
          repositories_skipped:

      - name: debug
        run: ls
        
      - name: store dist to metrics branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: lowlighter_metrics
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
